// Every line that is spoken aloud. The text lives in i18n.js under the same key.
// Recorded files go in assets/voice/<lang>/<file>.mp3 (or .m4a / .wav), where <file> is the
// key with dots replaced by dashes, e.g. feelReply.happy -> feelReply-happy.mp3.
// `demo: true` marks the lines heard in the pitch walkthrough: record these first.
window.VOICE_LINES = [
  { key: 'hubGreeting', char: 'Monki', screen: 'Jungle hub', tone: 'Warm, happy to see the child', demo: true },
  { key: 'missionSay', char: 'Monki', screen: 'Mission intro', tone: 'Playfully dismayed, then hopeful', demo: true },
  { key: 'gameSay', char: 'Monki', screen: 'Hallway game', tone: 'Curious, inviting', demo: true },
  { key: 'gameGood.0', char: 'Monki', screen: 'Hallway game', tone: 'Short burst of praise', demo: true },
  { key: 'gameGood.1', char: 'Monki', screen: 'Hallway game', tone: 'Short burst of praise', demo: true },
  { key: 'gameGood.2', char: 'Monki', screen: 'Hallway game', tone: 'Short burst of praise', demo: true },
  { key: 'gameGood.3', char: 'Monki', screen: 'Hallway game', tone: 'Short burst of praise', demo: false },
  { key: 'gameTry', char: 'Monki', screen: 'Hallway game', tone: 'Gentle encouragement, never disappointed', demo: false },
  { key: 'gameDone', char: 'Monki', screen: 'Hallway game', tone: 'Proud and grateful', demo: true },
  { key: 'realSay', char: 'Monki', screen: 'Real-world mission', tone: 'Inviting, a small challenge', demo: true },
  { key: 'celebrateSay', char: 'Monki', screen: 'Celebration', tone: 'Big celebration, cheering', demo: true },
  { key: 'stageSay.1', char: 'Monki', screen: 'Jungle hub (grows)', tone: 'Amazed discovery', demo: false },
  { key: 'stageSay.2', char: 'Monki', screen: 'Jungle hub (grows)', tone: 'Amazed discovery', demo: false },
  { key: 'stageSay.3', char: 'Monki', screen: 'Jungle hub (grows)', tone: 'Amazed discovery', demo: true },
  { key: 'stageSay.4', char: 'Monki', screen: 'Jungle hub (grows)', tone: 'Amazed discovery', demo: false },
  { key: 'mysterySay', char: 'Monki', screen: 'Secret friend', tone: 'Whispering a secret, excited', demo: false },
  { key: 'postcardSay', char: 'Secret friend (Nepal)', screen: 'Postcard from Nepal', tone: 'Friendly, a little mysterious. Different voice from Monki if possible', demo: true },
  { key: 'feelSay', char: 'Monki', screen: 'Feelings', tone: 'Soft, caring', demo: false },
  { key: 'feelReply.happy', char: 'Monki', screen: 'Feelings', tone: 'Happy together', demo: false },
  { key: 'feelReply.sad', char: 'Monki', screen: 'Feelings', tone: 'Gentle and comforting', demo: false },
  { key: 'feelReply.angry', char: 'Monki', screen: 'Feelings', tone: 'Calm, steady', demo: false },
  { key: 'feelReply.scared', char: 'Monki', screen: 'Feelings', tone: 'Reassuring, close', demo: false },
  { key: 'feelReply.excited', char: 'Monki', screen: 'Feelings', tone: 'Bouncy, excited', demo: false },
  { key: 'treeSay', char: 'Monki', screen: 'Banana tree', tone: 'Proud, counting together', demo: true },
  { key: 'friends.yanay', char: 'Monki', screen: 'Jungle hub (friends)', tone: 'Introducing a friend', demo: false },
  { key: 'friends.orbai', char: 'Monki', screen: 'Jungle hub (friends)', tone: 'Introducing a friend', demo: false },
  { key: 'friends.suala', char: 'Monki', screen: 'Jungle hub (friends)', tone: 'Introducing a friend', demo: false },
  { key: 'friends.palaiya', char: 'Monki', screen: 'Jungle hub (friends)', tone: 'Introducing a friend', demo: false },
  { key: 'huntSay', char: 'Monki', screen: 'Treasure hunt', tone: 'Adventure, let us go!', demo: true },
  { key: 'huntFound.red', char: 'Monki', screen: 'Treasure hunt', tone: 'Delighted', demo: true },
  { key: 'huntFound.soft', char: 'Monki', screen: 'Treasure hunt', tone: 'Delighted, cosy', demo: true },
  { key: 'huntFound.round', char: 'Monki', screen: 'Treasure hunt', tone: 'Delighted', demo: true },
  { key: 'huntFound.leaf', char: 'Monki', screen: 'Treasure hunt', tone: 'Delighted', demo: true },
  { key: 'breatheSay', char: 'Palaiya', screen: 'Breathe with Palaiya', tone: 'Slow, calm, wise old turtle', demo: true },
  { key: 'breatheIn', char: 'Palaiya', screen: 'Breathe with Palaiya', tone: 'Slow, stretched out over about 3 seconds', demo: true },
  { key: 'breatheOut', char: 'Palaiya', screen: 'Breathe with Palaiya', tone: 'Slow, stretched out over about 3 seconds', demo: true },
  { key: 'breatheDone', char: 'Palaiya', screen: 'Breathe with Palaiya', tone: 'Calm and proud', demo: true },
  { key: 'songsSay', char: 'Monki', screen: 'Songs and films', tone: 'Cheerful', demo: false },
  { key: 'songs.0.after', char: 'Monki', screen: 'Songs and films', tone: 'Inviting, creative', demo: false },
  { key: 'songs.1.after', char: 'Monki', screen: 'Songs and films', tone: 'Singing along energy', demo: false },
  { key: 'songs.2.after', char: 'Monki', screen: 'Songs and films', tone: 'Playful, stompy', demo: false },
  { key: 'songs.3.after', char: 'Monki', screen: 'Songs and films', tone: 'Quiet, bedtime', demo: false },
  { key: 'walkSay', char: 'Monki', screen: 'Go for a walk', tone: 'Outdoorsy, excited to go', demo: true },
  { key: 'walkItems.bird', char: 'Monki', screen: 'Go for a walk', tone: 'Naming it happily, one word', demo: true },
  { key: 'walkItems.dog', char: 'Monki', screen: 'Go for a walk', tone: 'Naming it happily, one word', demo: true },
  { key: 'walkItems.tree', char: 'Monki', screen: 'Go for a walk', tone: 'Naming it happily, one word', demo: true },
  { key: 'walkItems.flower', char: 'Monki', screen: 'Go for a walk', tone: 'Naming it happily, one word', demo: false },
  { key: 'walkItems.bus', char: 'Monki', screen: 'Go for a walk', tone: 'Naming it happily, one word', demo: false },
  { key: 'walkItems.cat', char: 'Monki', screen: 'Go for a walk', tone: 'Naming it happily, one word', demo: false },
  { key: 'walkItems.puddle', char: 'Monki', screen: 'Go for a walk', tone: 'Naming it happily, one word', demo: false },
  { key: 'walkItems.stone', char: 'Monki', screen: 'Go for a walk', tone: 'Naming it happily, one word', demo: false },
  { key: 'walkItems.bike', char: 'Monki', screen: 'Go for a walk', tone: 'Naming it happily, one word', demo: false },
  { key: 'walkItems.squirrel', char: 'Monki', screen: 'Go for a walk', tone: 'Naming it happily, one word', demo: false },
  { key: 'walkSongSay', char: 'Monki', screen: 'Walking song', tone: 'Proud, can not wait to share', demo: true },
  { key: 'foodSay', char: 'Monki', screen: 'Help Mommy', tone: 'Hungry and helpful', demo: true },
  { key: 'dishSay', char: 'Monki', screen: 'Help Mommy', tone: 'Encouraging', demo: true },
  { key: 'nightSay', char: 'Monki', screen: 'Goodnight', tone: 'Sleepy, yawning, warm', demo: false }
];
window.voiceFile = key => key.replace(/\./g, '-');
